# Generated by Django 6.0.1 on 2026-01-19 10:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NetworkNode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Название звена сети", max_length=255, unique=True, verbose_name="название"
                    ),
                ),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("factory", "Завод"),
                            ("retail", "Розничная сеть"),
                            ("individual", "Индивидуальный предприниматель"),
                        ],
                        default="factory",
                        help_text="Тип звена в сети",
                        max_length=20,
                        verbose_name="тип звена",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Контактный email",
                        max_length=255,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="email",
                    ),
                ),
                ("country", models.CharField(help_text="Страна расположения", max_length=100, verbose_name="страна")),
                ("city", models.CharField(help_text="Город расположения", max_length=100, verbose_name="город")),
                ("street", models.CharField(help_text="Улица расположения", max_length=255, verbose_name="улица")),
                (
                    "house_number",
                    models.CharField(help_text="Номер дома/строения", max_length=20, verbose_name="номер дома"),
                ),
                (
                    "product_name",
                    models.CharField(
                        help_text="Название продукта/оборудования", max_length=255, verbose_name="название продукта"
                    ),
                ),
                (
                    "product_model",
                    models.CharField(help_text="Модель продукта", max_length=255, verbose_name="модель продукта"),
                ),
                (
                    "product_release_date",
                    models.DateField(help_text="Дата выхода продукта на рынок", verbose_name="дата выхода продукта"),
                ),
                (
                    "debt_to_supplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Задолженность в денежном выражении (до копеек)",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="задолженность перед поставщиком",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Время создания записи", verbose_name="время создания"
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        default=0,
                        editable=False,
                        help_text="Уровень в иерархии сети (0 - завод)",
                        verbose_name="уровень в иерархии",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Поставщик оборудования (предыдущее звено в цепочке)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clients",
                        to="electronics_network.networknode",
                        verbose_name="поставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "звено сети",
                "verbose_name_plural": "звенья сети",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["supplier"], name="electronics_supplie_de113a_idx"),
                    models.Index(fields=["level"], name="electronics_level_589f29_idx"),
                    models.Index(fields=["city"], name="electronics_city_b32f27_idx"),
                    models.Index(fields=["country"], name="electronics_country_285dbe_idx"),
                    models.Index(fields=["debt_to_supplier"], name="electronics_debt_to_a6c862_idx"),
                ],
            },
        ),
    ]
