# Generated by Django 6.0.1 on 2026-01-19 10:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electronics_network", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="networknode",
            name="product_model",
        ),
        migrations.RemoveField(
            model_name="networknode",
            name="product_name",
        ),
        migrations.RemoveField(
            model_name="networknode",
            name="product_release_date",
        ),
        migrations.AlterField(
            model_name="networknode",
            name="email",
            field=models.EmailField(
                help_text="Контактный email",
                max_length=255,
                unique=True,
                validators=[django.core.validators.EmailValidator()],
                verbose_name="email",
            ),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Название продукта/оборудования", max_length=255, verbose_name="название продукта"
                    ),
                ),
                (
                    "model",
                    models.CharField(help_text="Модель продукта", max_length=255, verbose_name="модель продукта"),
                ),
                (
                    "release_date",
                    models.DateField(help_text="Дата выхода продукта на рынок", verbose_name="дата выхода продукта"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="время создания")),
            ],
            options={
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
                "ordering": ["-release_date", "name"],
                "unique_together": {("name", "model")},
            },
        ),
        migrations.AddField(
            model_name="networknode",
            name="products",
            field=models.ManyToManyField(
                help_text="Продукты, которые поставляет это звено",
                related_name="network_nodes",
                to="electronics_network.product",
                verbose_name="продукты",
            ),
        ),
        migrations.AddIndex(
            model_name="networknode",
            index=models.Index(fields=["email"], name="electronics_email_14aa19_idx"),
        ),
    ]
